#!/usr/bin/env python3
"""
TOR ANONYMOUS MANAGER  v3.0
UI dengan Rich, IP Leak Test, Service Control.

PRINSIP DESAIN (PENTING):
- Proxychains TIDAK PERNAH di-set sebagai default sistem/global.
  Tidak ada langkah di script ini yang menulis proxy ke environment
  variable global (http_proxy/https_proxy/ALL_PROXY) atau ke shell rc
  secara otomatis. npm install, npm run build, npm test, server lokal,
  python script lokal, dll — semua tetap jalan native, tidak lewat Tor.
- Proxychains hanya dipakai per-command, lewat wrapper (lihat tor_aliases.sh):
  pcurl, pcwget, pcpip, pcpython, dst. Jadi kamu pilih sendiri request
  mana yang mau disembunyikan IP-nya (misal request ke API luar),
  dan request lokal/dev tidak pernah ikut ke-proxy.
- Tor sendiri TIDAK membuat IP exit konsisten secara default: setiap kali
  proses tor restart / connect ulang, ia membentuk circuit baru dan exit
  node baru dipilih (meski exit country sama, IP-nya beda). Ini perilaku
  normal Tor, bukan bug. Kalau mau IP exit yang sama dipakai terus sampai
  diganti manual, gunakan menu "Lock Circuit" — itu hanya menahan dari
  rotasi otomatis (NEWNYM tidak dipanggil), tidak menjamin exit node sama
  100% selamanya (Tor bisa migrasi circuit lama yang sudah expired),
  tapi jauh lebih stabil dibanding restart berkali-kali.
"""

import os
import sys
import time
import json
import subprocess
from datetime import datetime

# ─────────────────────────────────────────
# CEK & AUTO-INSTALL DEPENDENCIES
# ─────────────────────────────────────────

def check_and_install_deps():
    deps = {
        'rich': 'rich',
        'requests': 'requests[socks]',
        'socks': 'pysocks',
    }
    missing = []
    for mod, pkg in deps.items():
        try:
            __import__(mod)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"[*] Installing: {', '.join(missing)}")
        subprocess.run(
            [sys.executable, '-m', 'pip', 'install', '--quiet'] + missing,
            check=True
        )
        print("[+] Done. Restarting...\n")
        os.execv(sys.executable, [sys.executable] + sys.argv)

check_and_install_deps()

import requests
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.columns import Columns
from rich.text import Text
from rich.prompt import Prompt, Confirm
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import box
from rich.align import Align

console = Console()

# ─────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────

TOR_CONFIG = {
    'socks_port': 9050,
    'control_port': 9051,
    'dns_port': 5353,
    'exclude_country': 'cn,ru,ir,kp',
}

PROXIES_TOR = {
    'http':  f'socks5h://127.0.0.1:{TOR_CONFIG["socks_port"]}',
    'https': f'socks5h://127.0.0.1:{TOR_CONFIG["socks_port"]}',
}

STATE_FILE = os.path.expanduser('~/.tor_manager_state.json')

PROXYCHAINS_CONFIG = """strict_chain
quiet_mode
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 127.0.0.1 9050
"""

TORRC_TEMPLATE = """# TOR CONFIG — Generated by tor_manager.py
SocksPort {socks_port}
ControlPort {control_port}
CookieAuthentication 1

DNSPort {dns_port}
AutomapHostsOnResolve 1

ExitNodes {exit_nodes}
ExcludeNodes {exclude_nodes}
StrictNodes 1

NumEntryGuards 3
EnforceDistinctSubnets 1

Log notice file /var/log/tor/notices.log
SafeLogging 1
"""

COUNTRIES = {
    'us': '🇺🇸 Amerika Serikat',
    'ca': '🇨🇦 Kanada',
    'de': '🇩🇪 Jerman',
    'fr': '🇫🇷 Perancis',
    'gb': '🇬🇧 Inggris',
    'sg': '🇸🇬 Singapura',
    'jp': '🇯🇵 Jepang',
    'au': '🇦🇺 Australia',
    'nl': '🇳🇱 Belanda',
    'se': '🇸🇪 Swedia',
    'no': '🇳🇴 Norwegia',
    'fi': '🇫🇮 Finlandia',
    'nz': '🇳🇿 Selandia Baru',
    'br': '🇧🇷 Brasil',
    'mx': '🇲🇽 Meksiko',
    'ch': '🇨🇭 Swiss',
    'at': '🇦🇹 Austria',
    'cz': '🇨🇿 Ceko',
    'ro': '🇷🇴 Romania',
    'pl': '🇵🇱 Polandia',
}

# ─────────────────────────────────────────
# STATE (circuit lock, dll)
# ─────────────────────────────────────────

def load_state():
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE) as f:
                return json.load(f)
        except Exception:
            pass
    return {'circuit_locked': False, 'exit_country': None}

def save_state(state):
    try:
        with open(STATE_FILE, 'w') as f:
            json.dump(state, f)
    except Exception:
        pass

# ─────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────

def run_cmd(cmd, check=False, shell=False):
    try:
        r = subprocess.run(
            cmd, capture_output=True, text=True,
            check=check, shell=shell
        )
        return r.stdout.strip(), r.stderr.strip(), r.returncode
    except Exception as e:
        return '', str(e), 1

def is_root():
    try:
        return os.geteuid() == 0
    except AttributeError:
        return False

def has_systemd():
    out, _, _ = run_cmd(['which', 'systemctl'])
    return bool(out)

def is_termux():
    return 'com.termux' in os.environ.get('PREFIX', '')

def _fmt_countries(csv: str) -> str:
    return ','.join(f'{{{c.strip()}}}' for c in csv.split(',') if c.strip())

# ─────────────────────────────────────────
# ENVIRONMENT SAFETY CHECK
# (Pastikan tidak ada proxy global yang ke-set tanpa sengaja,
#  supaya npm/pip/build lokal tidak pernah ketarik ke Tor.)
# ─────────────────────────────────────────

GLOBAL_PROXY_VARS = [
    'http_proxy', 'https_proxy', 'all_proxy',
    'HTTP_PROXY', 'HTTPS_PROXY', 'ALL_PROXY',
]

def check_global_proxy_leak():
    found = {k: os.environ[k] for k in GLOBAL_PROXY_VARS if os.environ.get(k)}
    return found

# ─────────────────────────────────────────
# CEK TOR & PROXYCHAINS (terinstall atau belum)
# ─────────────────────────────────────────

def check_system_deps():
    console.print()
    console.rule("[bold cyan]🔍 Cek System Dependencies[/bold cyan]")

    results = {}
    for tool in ['tor', 'proxychains', 'proxychains4']:
        out, _, _ = run_cmd(['which', tool])
        results[tool] = bool(out)

    tor_ok = results['tor']
    proxy_ok = results['proxychains'] or results['proxychains4']

    t = Table(box=box.ROUNDED, show_header=False, border_style="dim cyan")
    t.add_column("Tool", style="bold")
    t.add_column("Status")
    t.add_row("tor", "[green]✓ Terinstall[/green]" if tor_ok else "[red]✗ Belum ada[/red]")
    t.add_row("proxychains", "[green]✓ Terinstall[/green]" if proxy_ok else "[yellow]⚠ Belum ada[/yellow]")
    console.print(t)

    leaked_vars = check_global_proxy_leak()
    if leaked_vars:
        console.print(Panel(
            "[yellow]Environment variable proxy global terdeteksi:[/yellow]\n" +
            "\n".join(f"  {k}={v}" for k, v in leaked_vars.items()) +
            "\n\n[dim]Ini BUKAN dari script ini — kemungkinan di-set manual atau dari "
            "tool lain. Selama variable ini aktif, npm/pip/curl polos juga akan "
            "ikut lewat proxy itu. Unset kalau mau request lokal benar-benar native:[/dim]\n"
            "[green]unset " + " ".join(leaked_vars.keys()) + "[/green]",
            border_style="yellow", title="⚠ Cek Environment"
        ))

    to_install = []
    if not tor_ok:
        to_install.append('tor')
    if not proxy_ok:
        to_install.append('proxychains4')

    if to_install:
        console.print(f"\n[yellow]Perlu install: {', '.join(to_install)}[/yellow]")
        if Confirm.ask("Install sekarang?", default=True):
            _do_install(to_install)
        elif not tor_ok:
            console.print("[red]⚠ Tor tidak ada, beberapa fitur tidak akan berjalan.[/red]")
    else:
        console.print("\n[green]✓ Semua dependency OK![/green]")

def _do_install(packages):
    with Progress(
        SpinnerColumn(), TextColumn("[progress.description]{task.description}"),
        console=console, transient=True
    ) as prog:
        task = prog.add_task("Installing...", total=None)
        if is_termux():
            run_cmd(['pkg', 'update', '-y'])
            run_cmd(['pkg', 'install', '-y'] + packages)
        else:
            sudo = [] if is_root() else ['sudo']
            run_cmd(sudo + ['apt', 'update', '-y'])
            run_cmd(sudo + ['apt', 'install', '-y'] + packages)
        prog.update(task, description="[green]Done![/green]")
    console.print("[green]✓ Instalasi selesai![/green]")

# ─────────────────────────────────────────
# SERVICE CONTROL — TOR
# ─────────────────────────────────────────

def tor_status():
    try:
        import socket
        s = socket.socket()
        s.settimeout(1)
        s.connect(('127.0.0.1', TOR_CONFIG['socks_port']))
        s.close()
        return True
    except Exception:
        pass
    if has_systemd():
        _, _, code = run_cmd(['systemctl', 'is-active', '--quiet', 'tor'])
        return code == 0
    return False

def proxychains_status():
    """True hanya kalau config proxychains ADA dan mengarah ke tor.
    Ini tidak berarti aktif global — proxychains cuma jalan kalau
    dipanggil manual sebagai prefix command (proxychains <cmd>)."""
    for path in ['/etc/proxychains.conf', '/etc/proxychains4.conf']:
        if os.path.exists(path):
            with open(path) as f:
                if '9050' in f.read():
                    return True
    return False

def _wait_tor_ready(prog, task, timeout=120):
    import socket
    start = time.time()
    elapsed = 0
    while elapsed < timeout:
        try:
            s = socket.socket()
            s.settimeout(0.5)
            s.connect(('127.0.0.1', TOR_CONFIG['socks_port']))
            s.close()
            return True
        except OSError:
            pass
        elapsed = int(time.time() - start)
        prog.update(task, description=f"Menunggu Tor siap... {elapsed}s")
        time.sleep(0.5)
    return False

def start_tor():
    sudo = [] if is_root() else ['sudo']
    ok = False

    with Progress(
        SpinnerColumn(), TextColumn("[progress.description]{task.description}"),
        console=console, transient=True
    ) as prog:
        task = prog.add_task("Memulai Tor...", total=None)

        if has_systemd():
            prog.update(task, description="Mengaktifkan & memulai Tor via systemctl...")
            run_cmd(sudo + ['systemctl', 'enable', 'tor'], check=False)
            out, err, code = run_cmd(sudo + ['systemctl', 'restart', 'tor'], check=False)
            if code != 0:
                prog.update(task, description="systemctl gagal, coba via 'service'...")
                run_cmd(sudo + ['service', 'tor', 'restart'], check=False)
        elif is_termux():
            prog.update(task, description="Menjalankan tor (Termux)...")
            subprocess.Popen(['tor'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        else:
            prog.update(task, description="Menjalankan tor langsung...")
            log_file = open('/tmp/tor_start.log', 'w')
            subprocess.Popen(['tor'], stdout=log_file, stderr=log_file)

        prog.update(task, description="Menunggu Tor siap di port 9050...")
        ok = _wait_tor_ready(prog, task, timeout=120)
        prog.update(task, description="[green]Tor aktif![/green]" if ok else "[red]Timeout.[/red]")

    if ok:
        console.print(f"[green]✓ Tor aktif di port {TOR_CONFIG['socks_port']}![/green]")
        return True
    console.print("[red]✗ Tor tidak merespons setelah 120 detik.[/red]")
    return False

def stop_tor():
    sudo = [] if is_root() else ['sudo']
    if has_systemd():
        out, _, code = run_cmd(['systemctl', 'is-active', '--quiet', 'tor'])
        if code == 0:
            run_cmd(sudo + ['systemctl', 'stop', 'tor'])
    run_cmd(sudo + ['pkill', '-x', 'tor'])
    console.print("[yellow]✓ Tor dihentikan.[/yellow]")

# ─────────────────────────────────────────
# SETUP / UNSETUP / UNINSTALL — PROXYCHAINS
# ─────────────────────────────────────────

def setup_proxychains():
    """Tulis config proxychains. INI HANYA MENULIS FILE CONFIG —
    tidak menjadikan proxychains aktif secara global. Proxychains
    tetap harus dipanggil manual sebagai prefix (proxychains4 <cmd>)
    atau lewat wrapper di tor_aliases.sh."""
    sudo = [] if is_root() else ['sudo']
    tmp = '/tmp/proxychains_tor.conf'
    with open(tmp, 'w') as f:
        f.write(PROXYCHAINS_CONFIG)

    wrote_any = False
    for path in ['/etc/proxychains4.conf', '/etc/proxychains.conf']:
        # Hanya tulis ke path yang relevan dengan binary yang terinstall,
        # tapi aman juga ditulis ke keduanya kalau ada.
        out, err, code = run_cmd(sudo + ['cp', tmp, path])
        if code == 0:
            wrote_any = True

    os.remove(tmp)
    if wrote_any:
        console.print("[green]✓ Proxychains dikonfigurasi (quiet_mode aktif, hanya dipakai saat dipanggil manual).[/green]")
    else:
        console.print("[red]✗ Gagal menulis config proxychains. Pastikan proxychains terinstall.[/red]")

def unsetup_proxychains():
    """Matikan config tanpa uninstall package — backup config lalu
    arahkan ProxyList ke target yang tidak ada efeknya (default localhost
    9050 tetap ditulis tapi file di-rename jadi .disabled agar proxychains4
    fallback ke default bawaan paket / gagal jelas, bukan diam-diam aktif)."""
    sudo = [] if is_root() else ['sudo']
    any_done = False
    for path in ['/etc/proxychains4.conf', '/etc/proxychains.conf']:
        if os.path.exists(path):
            backup = path + '.bak'
            run_cmd(sudo + ['cp', path, backup])
            run_cmd(sudo + ['rm', '-f', path])
            any_done = True
    if any_done:
        console.print("[yellow]✓ Config proxychains di-unsetup (backup disimpan dengan suffix .bak).[/yellow]")
        console.print("[dim]Binary proxychains masih terinstall, tapi tanpa config ia akan error kalau dipanggil — aman.[/dim]")
    else:
        console.print("[dim]Tidak ada config proxychains untuk di-unsetup.[/dim]")

def uninstall_proxychains():
    if not Confirm.ask("Yakin uninstall proxychains sepenuhnya (package + config)?", default=False):
        console.print("[dim]Dibatalkan.[/dim]")
        return
    sudo = [] if is_root() else ['sudo']
    for path in ['/etc/proxychains4.conf', '/etc/proxychains.conf',
                 '/etc/proxychains4.conf.bak', '/etc/proxychains.conf.bak']:
        if os.path.exists(path):
            run_cmd(sudo + ['rm', '-f', path])

    if is_termux():
        run_cmd(['pkg', 'uninstall', '-y', 'proxychains-ng'])
    else:
        run_cmd(sudo + ['apt', 'remove', '-y', 'proxychains4', 'proxychains'])
    console.print("[yellow]✓ Proxychains diuninstall (package + config).[/yellow]")

# ─────────────────────────────────────────
# UNINSTALL — TOR
# ─────────────────────────────────────────

def uninstall_tor():
    if not Confirm.ask("Yakin uninstall Tor sepenuhnya (package + service + config)?", default=False):
        console.print("[dim]Dibatalkan.[/dim]")
        return
    sudo = [] if is_root() else ['sudo']

    stop_tor()

    if has_systemd():
        run_cmd(sudo + ['systemctl', 'disable', 'tor'], check=False)

    if is_termux():
        run_cmd(['pkg', 'uninstall', '-y', 'tor'])
    else:
        run_cmd(sudo + ['apt', 'remove', '-y', 'tor'])
        if Confirm.ask("Hapus juga config & data Tor (/etc/tor, /var/lib/tor)?", default=False):
            run_cmd(sudo + ['rm', '-rf', '/etc/tor', '/var/lib/tor'])

    if os.path.exists(STATE_FILE):
        os.remove(STATE_FILE)

    console.print("[yellow]✓ Tor diuninstall.[/yellow]")

# ─────────────────────────────────────────
# IP & LEAK TEST (real-time, andal)
# ─────────────────────────────────────────

IP_ENDPOINTS = [
    'https://api.ipify.org?format=json',
    'https://ifconfig.me/all.json',
    'https://icanhazip.com',
]

def _extract_ip(text, is_json):
    if is_json:
        try:
            data = json.loads(text)
            return data.get('ip') or data.get('ip_addr')
        except Exception:
            return None
    return text.strip() or None

def get_real_ip(timeout=8):
    for url in IP_ENDPOINTS:
        try:
            r = requests.get(url, timeout=timeout)
            if r.status_code != 200:
                continue
            is_json = 'json' in url
            ip = _extract_ip(r.text, is_json)
            if ip:
                return ip
        except Exception:
            continue
    return None

def get_tor_ip(timeout=15):
    if not tor_status():
        return None
    for url in IP_ENDPOINTS:
        try:
            r = requests.get(url, proxies=PROXIES_TOR, timeout=timeout)
            if r.status_code != 200:
                continue
            is_json = 'json' in url
            ip = _extract_ip(r.text, is_json)
            if ip:
                return ip
        except Exception:
            continue
    return None

def get_ip_info(use_tor=True, timeout=15):
    proxies = PROXIES_TOR if use_tor else None
    if use_tor and not tor_status():
        return None
    try:
        r = requests.get('https://ipinfo.io/json', proxies=proxies, timeout=timeout)
        if r.status_code == 200:
            return r.json()
    except Exception:
        pass
    return None

def check_ip_display():
    console.print()
    console.rule("[bold cyan]🌐 Informasi IP[/bold cyan]")

    with console.status("Mengambil IP asli (native, tanpa proxy)...", spinner="dots"):
        real_ip = get_real_ip()

    with console.status("Mengambil IP via Tor...", spinner="dots"):
        tor_info = get_ip_info(use_tor=True)

    t_real = Table(title="[bold red]⚠ IP ASLI (tanpa Tor)[/bold red]",
                   box=box.ROUNDED, border_style="red", show_header=False)
    t_real.add_column("Key", style="dim")
    t_real.add_column("Value", style="bold red")
    t_real.add_row("IP", real_ip or "Gagal mendapatkan")

    t_tor = Table(title="[bold green]🛡 IP via Tor[/bold green]",
                  box=box.ROUNDED, border_style="green", show_header=False)
    t_tor.add_column("Key", style="dim")
    t_tor.add_column("Value", style="bold green")

    if tor_info:
        t_tor.add_row("IP", tor_info.get('ip', 'N/A'))
        t_tor.add_row("Negara", tor_info.get('country', 'N/A'))
        t_tor.add_row("Kota", tor_info.get('city', 'N/A'))
        t_tor.add_row("Region", tor_info.get('region', 'N/A'))
        t_tor.add_row("ISP/Org", tor_info.get('org', 'N/A'))
        t_tor.add_row("Timezone", tor_info.get('timezone', 'N/A'))
    elif not tor_status():
        t_tor.add_row("Status", "[red]Tor tidak aktif[/red]")
    else:
        t_tor.add_row("Status", "[red]Gagal konek (timeout/circuit belum siap)[/red]")

    console.print(Columns([t_real, t_tor], equal=True, expand=True))

def ip_leak_test():
    console.print()
    console.rule("[bold cyan]🔬 IP Leak Test (real-time)[/bold cyan]")

    with console.status("Mengambil IP asli...", spinner="dots"):
        real_ip = get_real_ip()
    with console.status("Mengambil IP via Tor...", spinner="dots"):
        tor_ip = get_tor_ip()

    t = Table(box=box.DOUBLE_EDGE, border_style="cyan", show_header=True)
    t.add_column("Jenis", style="bold")
    t.add_column("IP", style="bold")
    t.add_column("Status", justify="center")

    leaked = bool(real_ip and tor_ip and real_ip == tor_ip)

    t.add_row("IP Asli", real_ip or "Gagal",
              "[red]⚠ EXPOSED[/red]" if leaked else "[dim]─[/dim]")

    if leaked:
        tor_status_cell = "[red]✗ BOCOR[/red]"
    elif tor_ip:
        tor_status_cell = "[green]✓ Aman[/green]"
    else:
        tor_status_cell = "[red]✗ Error[/red]"

    t.add_row("IP via Tor", tor_ip or "Gagal / Tor mati", tor_status_cell)
    console.print(t)

    if not tor_status():
        console.print(Panel(
            "[red bold]Tor tidak aktif! Start Tor dulu dari menu Service Control.[/red bold]",
            border_style="red", title="⚠ Peringatan"
        ))
    elif not tor_ip:
        console.print(Panel(
            "[red bold]Tor aktif tapi gagal ambil IP via Tor.\n"
            "Kemungkinan circuit belum terbentuk — tunggu beberapa detik dan coba lagi,\n"
            "atau cek apakah SocksPort benar-benar listen di 9050.[/red bold]",
            border_style="red", title="⚠ Gagal Konek"
        ))
    elif leaked:
        console.print(Panel(
            "[red bold]IP LEAK TERDETEKSI!\n"
            "IP asli sama dengan IP via Tor — traffic ini TIDAK lewat Tor.\n"
            "Cek apakah request ini benar-benar memakai proxies Tor, "
            "dan restart Tor kalau perlu.[/red bold]",
            border_style="red bold", title="🚨 LEAK!"
        ))
    else:
        console.print(Panel(
            f"[green bold]✓ AMAN — IP berhasil disembunyikan.\n"
            f"IP asli [red]{real_ip}[/red] tidak terlihat, "
            f"yang tampil ke pihak luar adalah [green]{tor_ip}[/green] via Tor.[/green bold]",
            border_style="green", title="✅ Aman"
        ))

# ─────────────────────────────────────────
# ROTATE, LOCK CIRCUIT & COUNTRY
# ─────────────────────────────────────────

def _find_cookie():
    for cp in ['/var/lib/tor/control_auth_cookie',
               '/run/tor/control.authcookie',
               '/tmp/tor/control.authcookie']:
        if os.path.exists(cp):
            try:
                with open(cp, 'rb') as f:
                    return f.read().hex()
            except PermissionError:
                pass
    return None

def _tor_send_signal(signal='NEWNYM'):
    import socket as _socket
    host = '127.0.0.1'
    port = TOR_CONFIG['control_port']
    cookie_hex = _find_cookie()

    with _socket.create_connection((host, port), timeout=5) as s:
        def send(cmd):
            s.sendall((cmd + '\r\n').encode())
            return s.recv(1024).decode(errors='replace')

        resp = send(f'AUTHENTICATE {cookie_hex}') if cookie_hex else send('AUTHENTICATE ""')
        if not resp.startswith('250'):
            raise RuntimeError(f'Auth gagal: {resp.strip()}')

        resp = send(f'SIGNAL {signal}')
        if not resp.startswith('250'):
            raise RuntimeError(f'Signal gagal: {resp.strip()}')
        send('QUIT')

def rotate_ip(force=False):
    state = load_state()
    if state.get('circuit_locked') and not force:
        console.print(Panel(
            "[yellow]Circuit sedang di-LOCK. IP exit tidak akan dirotasi otomatis.\n"
            "Kalau mau tetap rotate sekarang, konfirmasi di bawah.[/yellow]",
            border_style="yellow", title="🔒 Circuit Locked"
        ))
        if not Confirm.ask("Tetap rotate sekarang?", default=False):
            console.print("[dim]Dibatalkan, circuit tetap dikunci.[/dim]")
            return False

    try:
        _tor_send_signal('NEWNYM')
        with console.status("Menunggu sirkuit baru...", spinner="dots"):
            time.sleep(2)
            ip = get_tor_ip()
        console.print(f"[green]✓ IP dirotasi → [bold]{ip or 'Tunggu sebentar, coba cek IP lagi...'}[/bold][/green]")
        return True
    except Exception as e:
        console.print(f"[red]✗ Gagal rotate: {e}[/red]")
        console.print("[dim]Pastikan ControlPort 9051 aktif & CookieAuthentication 1 di torrc.[/dim]")
        return False

def toggle_circuit_lock():
    state = load_state()
    current = state.get('circuit_locked', False)
    new_val = not current
    state['circuit_locked'] = new_val
    save_state(state)
    if new_val:
        console.print(Panel(
            "[green]Circuit LOCKED.[/green]\n"
            "IP exit Tor sekarang TIDAK akan dirotasi otomatis. Restart Tor biasa "
            "tidak memanggil NEWNYM, jadi circuit yang sedang berjalan akan dipertahankan "
            "selama belum expired atau kamu rotate manual dengan konfirmasi paksa.\n\n"
            "[dim]Catatan jujur: Tor tetap bisa membentuk circuit baru sendiri kalau "
            "circuit lama mati/timeout — ini bukan jaminan IP 100% sama selamanya, "
            "tapi jauh lebih stabil dibanding rotate/restart berulang.[/dim]",
            border_style="green", title="🔒 Lock Aktif"
        ))
    else:
        console.print(Panel(
            "[yellow]Circuit UNLOCKED.[/yellow] Rotasi IP (manual/auto-rotate) berjalan normal lagi.",
            border_style="yellow", title="🔓 Lock Nonaktif"
        ))

def auto_rotate(interval=30, count=0):
    state = load_state()
    if state.get('circuit_locked'):
        console.print(Panel(
            "[red]Circuit sedang LOCKED. Auto-rotate akan terus minta konfirmasi tiap siklus, "
            "yang tidak praktis. Unlock dulu dari menu kalau mau auto-rotate jalan mulus.[/red]",
            border_style="red", title="🔒 Circuit Locked"
        ))
        if not Confirm.ask("Lanjutkan tetap (akan minta konfirmasi tiap rotasi)?", default=False):
            return

    console.print()
    console.rule(f"[bold cyan]🔄 Auto-Rotate setiap {interval}s[/bold cyan]")
    console.print("[dim]Tekan Ctrl+C untuk berhenti.[/dim]\n")

    counter = 0
    try:
        while True:
            if count > 0 and counter >= count:
                break
            counter += 1
            console.print(f"[bold cyan]─── Rotasi #{counter} ─ {datetime.now().strftime('%H:%M:%S')} ───[/bold cyan]")

            rotate_ip(force=True)
            new_info = get_ip_info()
            if new_info:
                console.print(
                    f"  IP Baru : [green bold]{new_info.get('ip')}[/green bold]"
                    f"  🌍 {new_info.get('country')} — {new_info.get('city')}"
                )

            if count == 0 or counter < count:
                for i in range(interval, 0, -1):
                    print(f"\r  [cyan]Rotasi berikutnya dalam {i}s...[/cyan]    ", end='', flush=True)
                    time.sleep(1)
                print()
    except KeyboardInterrupt:
        console.print("\n[yellow]Auto-rotate dihentikan.[/yellow]")

def change_country(code=None):
    if not code:
        t = Table(box=box.SIMPLE, show_header=False)
        t.add_column("Kode", style="bold cyan", width=6)
        t.add_column("Negara")
        for k, v in COUNTRIES.items():
            t.add_row(k, v)
        console.print(t)
        code = Prompt.ask("Kode negara").lower().strip()

    if code not in COUNTRIES:
        console.print(f"[red]Kode '{code}' tidak dikenal.[/red]")
        return False

    sudo = [] if is_root() else ['sudo']
    try:
        torrc_path = '/etc/tor/torrc'
        with open(torrc_path) as f:
            lines = f.readlines()

        new_lines = [l for l in lines if not l.startswith(('ExitNodes', 'ExcludeNodes'))]
        new_lines.append(f'ExitNodes {_fmt_countries(code)}\n')
        new_lines.append(f'ExcludeNodes {_fmt_countries(TOR_CONFIG["exclude_country"])}\n')

        tmp = '/tmp/torrc_new'
        with open(tmp, 'w') as f:
            f.writelines(new_lines)
        run_cmd(sudo + ['cp', tmp, torrc_path])
        os.remove(tmp)

        state = load_state()
        state['exit_country'] = code
        save_state(state)

        stop_tor()
        time.sleep(1)
        start_tor()

        console.print(f"[green]✓ Exit country diubah ke {COUNTRIES[code]}[/green]")
        console.print("[dim]Catatan: ganti negara = restart Tor = circuit baru, jadi IP exit juga baru "
                       "(meski di negara yang sama). Itu wajar.[/dim]")
        return True
    except Exception as e:
        console.print(f"[red]✗ Gagal: {e}[/red]")
        return False

# ─────────────────────────────────────────
# PROXYCHAINS HELPER (panduan, bukan auto-apply)
# ─────────────────────────────────────────

def proxychains_helper():
    console.print()
    console.print(Panel(
        "[bold cyan]Proxychains itu OPT-IN, bukan default global.[/bold cyan]\n\n"
        "Command biasa (npm install, npm run build, npm test, python3 app.py,\n"
        "server lokal, dll) TETAP NATIVE — tidak lewat Tor sama sekali.\n\n"
        "Kalau mau request tertentu lewat Tor (privasi saat akses API/website luar):\n"
        "  [green]proxychains4 curl https://api.ipify.org[/green]\n"
        "  [green]proxychains4 python3 script.py[/green]\n\n"
        "Atau pakai wrapper dari tor_aliases.sh (lebih singkat & ada log jelas):\n"
        "  [green]pcurl https://example.com[/green]      → curl lewat Tor\n"
        "  [green]pcpython script.py[/green]              → python3 lewat Tor\n"
        "  [green]pcpip install requests[/green]          → pip lewat Tor\n"
        "  [green]torip[/green] / [green]realip[/green] / [green]leakcheck[/green]  → cek IP cepat\n\n"
        "[dim]npm install -g, npm run build/test, server lokal (npm run dev, "
        "python -m http.server, dll) sengaja TIDAK dibungkus wrapper apa pun, "
        "supaya tidak ketarik ke Tor.[/dim]",
        border_style="cyan", title="🛡 Proxychains Guide"
    ))

# ─────────────────────────────────────────
# SERVICE PANEL
# ─────────────────────────────────────────

def service_panel():
    while True:
        console.print()
        console.rule("[bold cyan]⚙️  Service Control[/bold cyan]")

        t_active = tor_status()
        p_active = proxychains_status()
        state = load_state()

        t = Table(box=box.ROUNDED, show_header=False, border_style="dim")
        t.add_column("Service", style="bold", width=16)
        t.add_column("Status")
        t.add_column("Port/Info", style="dim")
        t.add_row("🧅 Tor",
                  "[green]● Aktif[/green]" if t_active else "[red]● Mati[/red]",
                  "SOCKS5 :9050  Control :9051")
        t.add_row("⛓ Proxychains",
                  "[green]● Config ada[/green]" if p_active else "[yellow]● Belum disetup[/yellow]",
                  "opt-in only — tidak otomatis aktif")
        t.add_row("🔒 Circuit Lock",
                  "[green]● Locked[/green]" if state.get('circuit_locked') else "[dim]● Unlocked[/dim]",
                  "cegah auto-rotate IP")
        console.print(t)
        console.print()

        opts = [
            "1.  Start Tor",
            "2.  Stop Tor",
            "3.  Restart Tor",
            "4.  Setup Proxychains",
            "5.  Unsetup Proxychains (matikan config, simpan backup)",
            "6.  Uninstall Proxychains (hapus total)",
            "7.  Uninstall Tor (hapus total)",
            "8.  Toggle Circuit Lock (kunci/buka IP exit)",
            "9.  Kembali ke menu utama",
        ]
        for o in opts:
            console.print(f"  [cyan]{o}[/cyan]")

        choice = Prompt.ask("\nPilihan", choices=[str(i) for i in range(1, 10)], default='9')

        if choice == '1':
            start_tor()
        elif choice == '2':
            stop_tor()
        elif choice == '3':
            stop_tor()
            time.sleep(1)
            start_tor()
        elif choice == '4':
            setup_proxychains()
        elif choice == '5':
            unsetup_proxychains()
        elif choice == '6':
            uninstall_proxychains()
        elif choice == '7':
            uninstall_tor()
        elif choice == '8':
            toggle_circuit_lock()
        elif choice == '9':
            break

        Prompt.ask("\n[dim]Enter untuk lanjut...[/dim]", default="")

# ─────────────────────────────────────────
# BANNER
# ─────────────────────────────────────────

def print_banner():
    os.system('clear' if os.name != 'nt' else 'cls')

    t_on = tor_status()
    p_on = proxychains_status()
    state = load_state()
    lock_on = state.get('circuit_locked', False)

    tor_badge = "[on green] ● TOR ON [/on green]" if t_on else "[on red] ● TOR OFF [/on red]"
    prx_badge = "[on green] ● PROXY READY [/on green]" if p_on else "[on red] ● PROXY NOT SET [/on red]"
    lock_badge = "[on yellow] ● CIRCUIT LOCKED [/on yellow]" if lock_on else "[dim]circuit unlocked[/dim]"

    banner = Text()
    banner.append("\n  ████████╗ ██████╗ ██████╗ \n", style="bold cyan")
    banner.append("     ██╔══╝██╔═══██╗██╔══██╗\n", style="bold cyan")
    banner.append("     ██║   ██║   ██║██████╔╝\n", style="bold cyan")
    banner.append("     ██║   ██║   ██║██╔══██╗\n", style="bold cyan")
    banner.append("     ██║   ╚██████╔╝██║  ██║\n", style="bold cyan")
    banner.append("     ╚═╝    ╚═════╝ ╚═╝  ╚═╝\n", style="bold cyan")
    banner.append("   ANONYMOUS MANAGER  v3.0\n", style="dim cyan")

    console.print(Align.center(banner))
    console.print(Align.center(Text.from_markup(f"  {tor_badge}   {prx_badge}\n")))
    console.print(Align.center(Text.from_markup(f"  {lock_badge}\n")))
    console.print(Align.center(Text.from_markup(
        f"[dim]  {datetime.now().strftime('%A, %d %b %Y  %H:%M:%S')}[/dim]\n"
    )))

# ─────────────────────────────────────────
# MENU UTAMA
# ─────────────────────────────────────────

def main_menu():
    while True:
        print_banner()

        menu_items = [
            ("1", "🌐", "Cek IP & Lokasi"),
            ("2", "🔬", "IP Leak Test (real-time)"),
            ("3", "🔄", "Rotasi IP (sekali)"),
            ("4", "⏱ ", "Auto-Rotate IP"),
            ("5", "🌍", "Ganti Exit Country"),
            ("6", "⚙ ", "Service Control (Tor / Proxychains / Lock)"),
            ("7", "⛓ ", "Cara Pakai Proxychains (opt-in guide)"),
            ("8", "🚪", "Keluar"),
        ]

        t = Table(box=box.SIMPLE_HEAD, show_header=False, border_style="dim cyan", padding=(0, 2))
        t.add_column("No", style="bold cyan", width=3)
        t.add_column("Icon", width=3)
        t.add_column("Menu")
        for no, icon, label in menu_items:
            t.add_row(no, icon, label)

        console.print(Panel(t, border_style="cyan", title="[bold cyan]MENU[/bold cyan]", padding=(0, 1)))

        choice = Prompt.ask("[cyan]Pilih menu[/cyan]", choices=[str(i) for i in range(1, 9)], show_choices=False)

        if choice == '1':
            check_ip_display()
        elif choice == '2':
            ip_leak_test()
        elif choice == '3':
            rotate_ip()
        elif choice == '4':
            try:
                interval = int(Prompt.ask("Interval rotasi (detik)", default="30"))
                count = int(Prompt.ask("Jumlah rotasi (0 = infinite)", default="0"))
            except ValueError:
                interval, count = 30, 0
            auto_rotate(interval, count)
        elif choice == '5':
            change_country()
        elif choice == '6':
            service_panel()
        elif choice == '7':
            proxychains_helper()
        elif choice == '8':
            console.print("\n[cyan]Stay safe! 🛡[/cyan]\n")
            break

        if choice != '8':
            Prompt.ask("\n[dim]Enter untuk kembali ke menu...[/dim]", default="")

# ─────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────

if __name__ == "__main__":
    check_system_deps()
    main_menu()
